### ISSUE TITLE
.htaccess files are ignored

### ISSUE THREAD

**Issue by meena-erian** [easyphp/easyphp-webserver#20]
First of all, thank you so much for making such an amazing project! I believe it's going to be exponentially more popular!

.htaccess files are commonly used along with php (Usually for mod_rewrite) to set directory-specific configuration such as internally redirecting all requests to an index.php and that's essential for all php frameworks. So, I believe it's supposed to be enabled by default.

**Comment by easyphp** [comment]
Yes it is. It works just fine.
Do you have more information ?

**Comment by meena-erian** [comment]
In a fresh installation of **EasyPHP-Webserver-14.1b2-setup.exe**, **.htaccess** files are ignored. 

I have to manually edit the webserver's configuration by going to file:

**EasyPHP-Webserver-14.1b2\binaries\httpserver\conf\httpd.conf**

Line `271` inside `<Directory "C:/Program Files (x86)/EasyPHP-Webserver-14.1b2/www">`

and edit 

`    AllowOverride None`

into:

`    AllowOverride All`

**Comment by easyphp** [comment]
Duly noted. Thanks.
